In [2]:
from collections import Counter
import pprint
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
from tqdm import tqdm

In [5]:
#f = open(f"./train_processed.txt", "r")
#sentences = f.readlines()
#f.close()
#print(len(sentences))

#sentences = [sentence.rstrip() for sentence in sentences if len(sentence) > 2]
#sentences[48]

483449


'Looking_VVG Good_AJ0 Feeling_VVG Good_AJ0 book_NN1'

In [6]:
#word_tag_pairs = []
#for sentence in sentences:
    #for word_tag_pair in sentence.split(" "):
        #if len(word_tag_pair.strip()) != 0:
         #   word_tag_pairs.append(word_tag_pair.strip())
#print(len(word_tag_pairs))
#print(word_tag_pairs[4])

8899819
by_PRP


In [7]:
#for pair in word_tag_pairs:
 #   try:
  #      tag = pair.split("_")[1]
   # except:
    #    print(pair)
     #   word_tag_pairs.remove(pair)

no
per


In [8]:
#all_words = [pair.split('_')[0] for pair in word_tag_pairs]
#all_tags = [pair.split('_')[1] for pair in word_tag_pairs]
#word_freq = Counter(all_words).most_common() # represent how many times each word appeared in dataset
#tag_freq = Counter(all_tags).most_common() # represent how many times each tag appeared in dataset
#train_words = [word[0] for word in word_freq] # all the words in the dataset
#tags = [word[0] for word in tag_freq] # all the tags in the dataset

In [9]:
#with open("./train_words.txt", "w+") as f:
 #   for word in train_words:
  #      f.write(f"{word}\n")
   # f.close()

In [10]:
#tags_to_index = {}
#for index in range(len(tag_freq)):
#    tags_to_index[tag_freq[index][0]] = index
#print(tags_to_index)
#tags_to_index["start"] = len(tags_to_index) #last tag is start tag
#np.save("tag_to_index.npy", tags_to_index)

#index_to_tags = {}
#for index in range(len(tag_freq)):
 #   index_to_tags[index] = tag_freq[index][0]
#index_to_tags[len(tags_to_index)] = "start" #last tag is start tag
#np.save("index_to_tag.npy", index_to_tags)
#print(index_to_tags)

{0: 'NN1', 1: 'AT0', 2: 'PRP', 3: 'AJ0', 4: 'NN2', 5: 'NP0', 6: 'AV0', 7: 'PNP', 8: 'CJC', 9: 'PRF', 10: 'VVI', 11: 'DT0', 12: 'VVN', 13: 'VVD', 14: 'CRD', 15: 'TO0', 16: 'DPS', 17: 'VM0', 18: 'VBD', 19: 'VVG', 20: 'CJS', 21: 'VBZ', 22: 'VVB', 23: 'VVZ', 24: 'POS', 25: 'XX0', 26: 'CJT', 27: 'AVP', 28: 'VBI', 29: 'DTQ', 30: 'NN0', 31: 'VBB', 32: 'NN1-VVB', 33: 'AJ0-NN1', 34: 'VHD', 35: 'ORD', 36: 'NP0-NN1', 37: 'VHZ', 38: 'VHB', 39: 'VBN', 40: 'PNI', 41: 'PNQ', 42: 'NN1-AJ0', 43: 'PRP-AVP', 44: 'EX0', 45: 'VVN-VVD', 46: 'AJC', 47: 'AVQ', 48: 'VVB-NN1', 49: 'VVD-VVN', 50: 'VHI', 51: 'NN1-NP0', 52: 'VVG-AJ0', 53: 'PNX', 54: 'UNC', 55: 'AJS', 56: 'NN2-VVZ', 57: 'VDB', 58: 'VDD', 59: 'VVG-NN1', 60: 'VVN-AJ0', 61: 'VBG', 62: 'AVP-PRP', 63: 'CJT-DT0', 64: 'AV0-AJ0', 65: 'NN1-VVG', 66: 'AJ0-AV0', 67: 'ITJ', 68: 'VVZ-NN2', 69: 'VDI', 70: 'PRP-CJS', 71: 'AJ0-VVG', 72: 'CJS-AVQ', 73: 'ZZ0', 74: 'VDZ', 75: 'CJS-PRP', 76: 'AJ0-VVN', 77: 'DT0-CJT', 78: 'VHG', 79: 'AJ0-VVD', 80: 'VDN', 81: 'VHN', 82:

In [3]:
f = open(f"./test_processed.txt", "r")
sentences = f.readlines()
f.close()

sentences = [sentence.rstrip() for sentence in sentences if len(sentence) > 2]
print(len(sentences))
sentences[48]

199464


'The_AT0 Security_NN1 Service_NN1 is_VBZ part_NN1 of_PRF the_AT0 Defence_NN1 Forces_NN2 of_PRF the_AT0 country_NN1'

In [4]:
index_to_tags = np.load("index_to_tag.npy",allow_pickle=True).item()
tags_to_index = np.load("tag_to_index.npy",allow_pickle=True).item()
print(index_to_tags)

{0: 'NN1', 1: 'AT0', 2: 'PRP', 3: 'AJ0', 4: 'NN2', 5: 'NP0', 6: 'AV0', 7: 'PNP', 8: 'CJC', 9: 'PRF', 10: 'VVI', 11: 'VVN', 12: 'DT0', 13: 'VVD', 14: 'CRD', 15: 'TO0', 16: 'DPS', 17: 'VVG', 18: 'VM0', 19: 'VBD', 20: 'CJS', 21: 'VBZ', 22: 'VVB', 23: 'VVZ', 24: 'CJT', 25: 'AVP', 26: 'POS', 27: 'XX0', 28: 'VBI', 29: 'DTQ', 30: 'NN0', 31: 'VBB', 32: 'VHD', 33: 'ORD', 34: 'NN1-VVB', 35: 'VHZ', 36: 'AJ0-NN1', 37: 'VHB', 38: 'PNI', 39: 'NP0-NN1', 40: 'VBN', 41: 'PNQ', 42: 'EX0', 43: 'AVQ', 44: 'AJC', 45: 'VHI', 46: 'PRP-AVP', 47: 'NN1-AJ0', 48: 'VVN-VVD', 49: 'VVD-VVN', 50: 'VVB-NN1', 51: 'PNX', 52: 'UNC', 53: 'AJS', 54: 'NN1-NP0', 55: 'VDB', 56: 'VDD', 57: 'VVG-AJ0', 58: 'VBG', 59: 'NN2-VVZ', 60: 'VVG-NN1', 61: 'VVN-AJ0', 62: 'ITJ', 63: 'VDI', 64: 'AVP-PRP', 65: 'AV0-AJ0', 66: 'CJT-DT0', 67: 'ZZ0', 68: 'VDZ', 69: 'NN1-VVG', 70: 'AJ0-AV0', 71: 'VVZ-NN2', 72: 'AJ0-VVG', 73: 'PRP-CJS', 74: 'CJS-AVQ', 75: 'AJ0-VVN', 76: 'CJS-PRP', 77: 'VHG', 78: 'DT0-CJT', 79: 'VDN', 80: 'VHN', 81: 'AJ0-VVD', 82:

In [5]:
em_probs = np.load("word_given_tag.npy",allow_pickle=True).item()
tr_probs = np.load("Trans_Matrix.npy",allow_pickle=True)

print(em_probs["VVI"]["make"])
print(em_probs["VVI"]["encourage"])

5377
422


In [11]:
gt_tags = []
pred_tags = []
countx=0

for sentence in tqdm(sentences):
    prev_tag = "start"
    
    for word_tag_pair_idx in range(len(sentence.split(" "))):
        word_tag_pair = sentence.split(" ")[word_tag_pair_idx]
        if len(word_tag_pair.strip()) != 0:
            #print(word_tag_pair)
            word = word_tag_pair.split("_")[0]
            gt_tag = tags_to_index[word_tag_pair.split("_")[1]]
    
            possible_tags = []
            for idx in range(len(index_to_tags)):
                try:
                    emprob_for_this_word_tag = em_probs[index_to_tags[idx]][word]
                except:
                    emprob_for_this_word_tag = 0

                tr_prob = tr_probs[tags_to_index[prev_tag], idx]

                possible_tags.append(emprob_for_this_word_tag*tr_prob)

            possible_tags = np.array(possible_tags)
            if np.max(possible_tags) == 0:
                predicted_tag = index_to_tags[np.argmax(tr_probs[tags_to_index[prev_tag]])]
            else:
                predicted_tag = index_to_tags[np.argmax(possible_tags)]
            
#             total_pred += 1
#             if (tags_to_index[predicted_tag] == gt_tag):
#                 correct_pred += 1
            gt_tags.append(gt_tag)
            pred_tags.append(tags_to_index[predicted_tag])
            if predicted_tag in word_tag_pair.split("_")[1]:
                countx+=1

            prev_tag = predicted_tag
            #print(f"{predicted_tag}, {index_to_tags[gt_tag]}")

100%|██████████| 199464/199464 [06:39<00:00, 499.83it/s] 


In [15]:
#count_cp = 0
#for index in range(len(gt_tags)):
 #   if pred_tags[index] == gt_tags[index]:
        # correct prediction
  #      count_cp += 1

accuracy = countx/len(gt_tags)
print(f"Accuracy = {accuracy*100}%")
print(f"The total data has  = {len(gt_tags)}")
print(f"The no of correct predictions = {countx}")
print(f"The no of incorrect predictions = {len(gt_tags)-countx}")
#print(countx/len(gt_tags))
#print(gt_tags[9])
#print(pred_tags[9])

Accuracy = 91.25108850614026%
The total data has  = 3528919
The no of correct predictions = 3220177
The no of incorrect predictions = 308742


In [16]:
new_sentence = "The Security Service is part of the Defence Forces of the country"

for word_tag_pair_idx in range(len(new_sentence.split(" "))):
        word_tag_pair = new_sentence.split(" ")[word_tag_pair_idx]
        word = word_tag_pair.split("_")[0]

        possible_tags = []
        for idx in range(len(index_to_tags)):
            try:
                emprob_for_this_word_tag = em_probs[index_to_tags[idx]][word]
            except:
                emprob_for_this_word_tag = 0

            tr_prob = tr_probs[tags_to_index[prev_tag], idx]

            possible_tags.append(emprob_for_this_word_tag*tr_prob)

        possible_tags = np.array(possible_tags)
        if np.max(possible_tags) == 0:
            predicted_tag = "UNC"
        else:
            predicted_tag = index_to_tags[np.argmax(possible_tags)]

        print(f"{word}: {predicted_tag}")
        prev_tag = predicted_tag

The: AT0
Security: NN1
Service: NN1
is: VBZ
part: NN1
of: PRF
the: AT0
Defence: NN1
Forces: NN2
of: PRF
the: AT0
country: NN1


In [17]:
# confusion matrix

cm = confusion_matrix(gt_tags, pred_tags)
np.savetxt("hmm_confusion_matrix.txt", cm, fmt="%d", delimiter="\t")
print(cm)
print(cm[20,20])

[[512224   2051   1395 ...      0      0      0]
 [    23 337605      0 ...      0      0      0]
 [   252      9 277520 ...      0      0      0]
 ...
 [    13     11      4 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
30060


End
